// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.controller;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JPanel;

import client.communication.ChatClient;
import client.gui.LoginPanel;
import client.model.LoginData;

/************************************************************/
/**
 * Acts as a controllor between the create account data and the create account
 * panel
 * 
 */
public class CreateAccountControl implements ActionListener
{

	public CreateAccountControl(JPanel container, ChatClient client)
	{
		this.client = client;
		this.container = container;

	}

	private ChatClient client;
	private JPanel container;

	@Override
	public void actionPerformed(ActionEvent ae)
	{
		String command = ae.getActionCommand();

		if (command == "Cancel")
		{
			CardLayout cardLayout = (CardLayout) container.getLayout();

			cardLayout.show(container, "1");

		} else if (command == "Submit")
		{
			// Get the username and password the user entered.
			LoginPanel loginPanel = (LoginPanel) container.getComponent(1);
			LoginData data = new LoginData(loginPanel.getUsername(), loginPanel.getPassword());

			// Check the validity of the information locally first.
			if (data.getUsername().equals("") || data.getPassword().equals(""))
			{
				displayError("You must enter a username and password.");
				return;
			} else
			{
				try
				{
					client.sendToServer(data);
				} catch (IOException e)
				{
					client.connectionException(e);
				}
			}

			// Submit the login information to the server.

		}
	}

	public void displayError(String error)
	{
		LoginPanel loginPanel = (LoginPanel) container.getComponent(1);
		loginPanel.setError(error);

	}

}
