// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.controller;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;

/************************************************************/
/**
 * 
 */
public class PlayingControl
{
	/**
	 * 
	 */
	private JPanel container;

	public PlayingControl(JPanel container)
	{

	}

	public void actionPerformed(ActionEvent ae)
	{

	}

	public void displayStatus(String status)
	{

	}

}
