// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.controller;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;

/************************************************************/
/**
 * 
 */
public class StartGameControl
{
	/**
	 * 
	 */
	private JPanel container;

	public StartGameControl(JPanel container)
	{

	}

	public void actionPerformed(ActionEvent ae)
	{

	}

	/**
	 * 
	 */
	public void gameStarted()
	{

	}

	public void displayError(String error)
	{

	}

}
