// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.panels;

import javax.swing.*;

/************************************************************/
/**
 * 
 */
public class PlayingPanel extends JPanel
{
	/**
	 * 
	 */
	private JButton opponentGridBtn;
	private JButton submitMoveBtn;
	private JButton leaveGameBtn;
	private JLabel gameStatusLbl;

	
	public void setStatusLbl(String status)
	{
		
	}
}
