// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.panels;

import javax.swing.*;
import client.controller.StartGameControl;

/************************************************************/
/**
 * 
 */
public class StartGamePanel extends JPanel
{

	private JButton logOut;
	private JLabel options;
	private JButton createGame;
	private JLabel defaultsChecked;
	private JButton findGame;

	public StartGamePanel(StartGameControl sgc)
	{
		
	}

	public void setError(String error)
	{
		
	}

	public Boolean getOptions()
	{
		return null;
	}

	public Boolean getDefaultsChecked()
	{
		return null;
	}
}
