// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.panels;

import javax.swing.*;

/************************************************************/
/**
 * 
 */
//builds the gui for match history panel should be swapped from the Playing Control class
public class ViewMatchHistoryPanel extends JPanel
{
	/**
	 * 
	 */
	private String username;
	private int timeElapsed;
	private int movesTaken;
	private int shipsSunk;

	public String getUsername()
	{
		return username;

	}

	public int getTime()
	{
		return timeElapsed;

	}

	public int getMoves()
	{
		return movesTaken;

	}

	public int getShipsSunk()
	{
		return shipsSunk;

	}
}
