// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package database;

import java.io.Serializable;

/************************************************************/
/**
 * Stores data about the user
 */
class User implements Serializable
{
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String password;

	/**
	 * 
	 * @return
	 */
	public String getUsername()
	{

		return username;
	}

	/**
	 * 
	 * @return
	 */
	public String getPassword()
	{

		return password;
	}

	/**
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{

		this.username = username;
	}

	/**
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{

		this.password = password;
	}

	/**
	 * 
	 * @param username
	 * @param password
	 */
	public User(String username, String password)
	{

		setUsername(username);
		setPassword(password);
	}
};
