// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.data;

/************************************************************/
/**
 * 
 */
public class PlayingData
{

	private String opponent;

	public void setOpponent(Boolean opponent)
	{

	}

	public Boolean getOpponent()
	{

		// probably need to change return type
		return null;
	}
}
