// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.data;

import java.awt.geom.Rectangle2D;

/************************************************************/
/**
 * 
 */
public class PlayingData
{

	private String opponent;
	private Rectangle2D square;
	
	
	public void setOpponent(Boolean opponent)
	{

	}

	public String getOpponent()
	{

		// probably need to change return type
		return opponent;
	}
	
	public Rectangle2D getSquare()
	{
		return square;
	}

	// Setters for the username and password.
	public void setSquare(Rectangle2D square)
	{
		this.square = square;
	}
}
