// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package client.data;

/************************************************************/
/**
 * 
 */
public class StartGameData
{

	private boolean options;

	public StartGameData()
	{

	}
	public StartGameData(boolean val)
	{
		
	}
	public Boolean getOptions()
	{
		return options;
	}

	public void setOptions(Boolean options)
	{
	}

	public void setDefaultOptions(Boolean options)
	{
	}

	
}
